# Generated by Django 2.2.1 on 2019-05-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_candidato_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
    ]
