# Generated by Django 2.2.1 on 2019-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_remove_candidato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(null=True, upload_to='Demoday\\media'),
        ),
    ]
