# Generated by Django 2.2.1 on 2019-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_auto_20190506_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='dt_nascimento',
            new_name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=15),
        ),
    ]
