# Generated by Django 2.2.1 on 2019-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_auto_20190506_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='dt_nascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='jatrabalha',
            new_name='ja_trabalha',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino'), ('o', 'Outro')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=''),
        ),
    ]
