# Generated by Django 2.2.1 on 2019-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0004_candidato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
