# Generated by Django 2.2.1 on 2019-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0004_auto_20190519_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino'), ('o', 'Outro')], default=' ', max_length=11),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=' '),
        ),
    ]
