# Generated by Django 2.2.1 on 2019-05-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0004_auto_20190517_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='jatrabalha',
            new_name='ja_trabalha',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=0),
        ),
    ]
