# Generated by Django 2.2.1 on 2019-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0005_auto_20190517_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=''),
        ),
    ]
