# Generated by Django 2.2.1 on 2019-05-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0005_auto_20190521_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
    ]
