# Generated by Django 2.2.1 on 2019-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0006_remove_candidato_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='genero',
            new_name='gênero',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='ja_trabalha',
            new_name='já_trabalha',
        ),
        migrations.AddField(
            model_name='candidato',
            name='conhecimentos',
            field=models.TextField(default='Coloque aqui suas habilidades e aptidões'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='educação',
            field=models.TextField(default='Coloque aqui quais cursos você já fez e quando foram finalizados'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default='Nome Completo', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default='SEGUINDO UM MODELO DE CURRICULO: Coloque aqui suas experiencias proficionais, cargos'),
        ),
    ]
