# Generated by Django 2.2.1 on 2019-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0007_auto_20190521_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=' Coloque aqui suas experiencias proficionais, cargos '),
        ),
    ]
