# Generated by Django 2.2.1 on 2019-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0008_auto_20190521_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='educação',
            new_name='educacao',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='gênero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='já_trabalha',
            new_name='ja_trabalha',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default='Coloque aqui suas experiencias proficionais, cargos'),
        ),
    ]
