# Generated by Django 2.2.1 on 2019-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0009_auto_20190521_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='conhecimentos',
            field=models.TextField(default='Coloque aqui suas habilidades e aptidões', max_length=10000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='educacao',
            field=models.TextField(default='Coloque aqui quais cursos você já fez e quando foram finalizados', max_length=10000),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default='Coloque aqui suas experiencias proficionais, cargos', max_length=10000),
        ),
    ]
